name: ecs-tag-shift
description: Shift ECS tags based on mode, file, container, and image inputs
author: dev-shimada
inputs:
  mode:
    description: |
      Mode of ecs-tag-shift (e.g., "task" or "container")
    required: true
  file:
    description: |
      Target file path
    required: true
  container:
    description: |
      Container name
    required: false
  image:
    description: |
      Image name
    required: false

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0

    - name: Install ecs-tag-shift
      shell: bash
      run: go install github.com/dev-shimada/ecs-tag-shift@latest

    
    - name: Show version
      shell: bash
      run: ecs-tag-shift -v

    - name: Execute ecs-tag-shift
      shell: bash
      if: |
        ! fromJSON(inputs.skip_push)
      env:
        MODE: ${{ inputs.mode }}
        FILE: ${{ inputs.file }}
        CONTAINER: ${{ inputs.container }}
        IMAGE: ${{ inputs.image }}
      run: |
        ecs-tag-shift \
          --mode "$MODE" \
          --file "$FILE" \
          --container "$CONTAINER" \
          --image "$IMAGE" 
