name: ecs-tag-shift
description: Shift ECS tags based on mode, file, container, and image inputs
author: dev-shimada
inputs:
  mode:
    description: |
      Mode of ecs-tag-shift (e.g., "task" or "container")
    required: true
  file:
    description: |
      Target file path
    required: true
  tag: 
    description: |
      Tag value
    required: true
  container:
    description: |
      Container name
    required: false
  image:
    description: |
      Image name
    required: false

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.25.4'

    - name: Install ecs-tag-shift
      shell: bash
      run: go install github.com/dev-shimada/ecs-tag-shift/cmd/ecs-tag-shift@latest

    - name: Execute ecs-tag-shift
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        FILE: ${{ inputs.file }}
        TAG: ${{ inputs.tag }}
        CONTAINER: ${{ inputs.container }}
        IMAGE: ${{ inputs.image }}
      run: |
        ecs-tag-shift shift \
          "$FILE" \
          --mode "$MODE" \
          --container "$CONTAINER" \
          --image "$IMAGE" \
          --tag "$TAG" \
          -w
